// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu2Ley-mmvXp7uEr2H9t4StSx3uK2Tu-M',
    appId: '1:656514380367:web:919922c785839c4ddef03a',
    messagingSenderId: '656514380367',
    projectId: 'my-portfolio-igu',
    authDomain: 'my-portfolio-igu.firebaseapp.com',
    storageBucket: 'my-portfolio-igu.firebasestorage.app',
    measurementId: 'G-30ERV93NZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHL9UZEFdGvR2192P9C5-m3ol3qILmU7g',
    appId: '1:656514380367:android:d96d42908614847bdef03a',
    messagingSenderId: '656514380367',
    projectId: 'my-portfolio-igu',
    storageBucket: 'my-portfolio-igu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq2KfSNNclkDu3h1LHE2Pk93L3VfUAJ14',
    appId: '1:656514380367:ios:3a4432a30a649d01def03a',
    messagingSenderId: '656514380367',
    projectId: 'my-portfolio-igu',
    storageBucket: 'my-portfolio-igu.firebasestorage.app',
    iosBundleId: 'com.example.timeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq2KfSNNclkDu3h1LHE2Pk93L3VfUAJ14',
    appId: '1:656514380367:ios:3a4432a30a649d01def03a',
    messagingSenderId: '656514380367',
    projectId: 'my-portfolio-igu',
    storageBucket: 'my-portfolio-igu.firebasestorage.app',
    iosBundleId: 'com.example.timeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu2Ley-mmvXp7uEr2H9t4StSx3uK2Tu-M',
    appId: '1:656514380367:web:70f10bee847f4782def03a',
    messagingSenderId: '656514380367',
    projectId: 'my-portfolio-igu',
    authDomain: 'my-portfolio-igu.firebaseapp.com',
    storageBucket: 'my-portfolio-igu.firebasestorage.app',
    measurementId: 'G-NG6T5LTN96',
  );
}
